# Generated by Django 3.1.1 on 2020-09-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('pushed_product', models.CharField(max_length=50)),
                ('callback', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
